[package]
name = "untitled10"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
async-channel = { version = "2.1" }
clap = { version = "4.4", features = ["derive"] }
futures-util = { version = "0.3" }
tokio = { version = "1.0", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"
futures = "0.3.31"
log = "0.4.25"
env_logger = "0.11.6"
rand = "0.9.0"
unicode-segmentation = "1.12.0"
rand_chacha = "0.9.0"
hex = "0.4.3"
warp = { version = "0.3.7", features = ["tls"] }
tokio-rustls = "0.26.1"
rustls = "0.23.22"
openssl = { version = "0.10.70", features = ["vendored"] }
