[package]
name = "untitled10"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
async-channel = { version = "2.1" }
axum = { version = "0.8.1", features = ["tokio", "ws"] }
clap = { version = "4.4", features = ["derive"] }
futures-util = { version = "0.3" }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"
futures = "0.3.31"
log = "0.4.25"
env_logger = "0.11.6"
rand = "0.9.0"
unicode-segmentation = "1.12.0"
rand_chacha = "0.9.0"
hex = "0.4.3"
